services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"