version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:16.5.3-ce.0
    hostname: gitlab.local
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.72:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - "8929:8929"
      - "443:443"
      - "2424:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    shm_size: "256m"
# пасс 7zN]6wn-bF3N9YE
