apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: footest-rs-1
  labels:
    app: footest-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: footest-app
          image: morozip/footest:0.1
