apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: footest-rs-2
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - footest
          - http-server
      - key: env
        operator: Exists
  template:
    metadata:
      labels:
        app: footest
        env: dev
    spec:
      containers:
        - name: footest-app
          image: morozip/footest:0.1
