apiVersion: apps/v1
kind: Deployment
metadata:
  name: footest
  labels:
    app: footest
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: footest-app
          image: morozip/footest:0.2
          ports:
            - containerPort: 8000
      